version: '3'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      # AWS
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4572:4572" # s3
      - "4576:4576" # sqs
    volumes:
      - ./localstack/data:/tmp/localstack/data
      - ./localstack/s3:/root/localstack/s3